apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: osel1y7u7-java-quarkus
  janus-idp.io/tekton: osel1y7u7-java-quarkus
  backstage.io/kubernetes-id: osel1y7u7-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: osel1y7u7-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
